version: '3.8'

services:
  app-server:
    container_name: app-server
    build:
      context: ./apps/app-server
      dockerfile: ../../container/Dockerfile.app-server
      target: production
      args:
        NODE_ENV: 'production'
        BASE_IMAGE: node:16.15-buster-slim
    environment:
      NODE_ENV: 'production'
      PORT: ${APP_PORT:-3010}
    volumes:
      - ./apps/app-server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - ${APP_PORT:-3010}:${APP_PORT:-3010}
    command: npm run build
    restart: always

  mongodb-service:
    container_name: mongodb-service
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_DATA: /data/db
    volumes:
    - ./apps/api-server/mongodata:/data/db

  api-server:
    container_name: api-server
    build:
      context: ./apps/api-server
      dockerfile: ../../container/Dockerfile.api-server
      target: production
      args:
        NODE_ENV: 'production'
        BASE_IMAGE: node:16.15-buster-slim
    environment:
      NODE_ENV: 'production'
      PORT: ${API_PORT:-3020}
    volumes:
      - ./apps/api-server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - ${API_PORT:-3020}:${API_PORT:-3020}
    command: npm run start:prod
    restart: always
    depends_on:
      - mongodb-service

networks:
  default:
      name: server_backend
