export const tenantStub = () => {
  return [
    {
      _id: '64391d05b9de5e7f1ad13d0e',
      type: 'State',
      description: '2',
      name: 'abc',
      email: 'abc@hm.com',
      contactNumber: 12345,
      address: 'abc',
      state: 'abc',
      city: 'abc',
      zipCode: 1234,
      timeZone: 'est',
      domainName: 'abc',
      databaseName: 'abc',
      clientLogo: 'logo-small.svg',
      accentColor: 'abc',
      programs: 'Career services',
      additionalFeature: 'Toolkit',
      modifiedBy: 0,
      createdAt: '2023-04-14T09:29:41.112Z',
      modifiedAt: '2023-04-14T09:29:41.112Z',
      createdBy: 0,
      isDelete: false,
      isArchive: true,
      stateRegion: 'abc',
    },
  ];
};
