export const timeZoneStud = [
  {
    _id: '644a50b6721097dc09aa54bb',
    value: 'Dateline Standard Time',
    abbr: 'DST',
    offset: '-12',
    isdst: false,
    text: '(UTC-12:00) International Date Line West',
    utc: ['Etc/GMT+12'],
    __v: 0,
  },
  {
    _id: '644a50b6721097dc09aa54bc',
    value: 'UTC-11',
    abbr: 'U',
    offset: '-11',
    isdst: false,
    text: '(UTC-11:00) Coordinated Universal Time-11',
    utc: ['Etc/GMT+11', 'Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago'],
    __v: 0,
  },
  {
    _id: '644a50b6721097dc09aa54bd',
    value: 'Hawaiian Standard Time',
    abbr: 'HST',
    offset: '-10',
    isdst: false,
    text: '(UTC-10:00) Hawaii',
    utc: [
      'Etc/GMT+10',
      'Pacific/Honolulu',
      'Pacific/Johnston',
      'Pacific/Rarotonga',
      'Pacific/Tahiti',
    ],
    __v: 0,
  },
  {
    _id: '644a50b6721097dc09aa54be',
    value: 'Alaskan Standard Time',
    abbr: 'AKDT',
    offset: '-8',
    isdst: true,
    text: '(UTC-09:00) Alaska',
    utc: [
      'America/Anchorage',
      'America/Juneau',
      'America/Nome',
      'America/Sitka',
      'America/Yakutat',
    ],
    __v: 0,
  },
  {
    _id: '644a50b6721097dc09aa54bf',
    value: 'Pacific Standard Time (Mexico)',
    abbr: 'PDT',
    offset: '-7',
    isdst: true,
    text: '(UTC-08:00) Baja California',
    utc: ['America/Santa_Isabel'],
    __v: 0,
  },
  {
    _id: '644a50b6721097dc09aa54c0',
    value: 'Pacific Daylight Time',
    abbr: 'PDT',
    offset: '-7',
    isdst: true,
    text: '(UTC-07:00) Pacific Daylight Time (US & Canada)',
    utc: ['America/Los_Angeles', 'America/Tijuana', 'America/Vancouver'],
    __v: 0,
  },
  {
    _id: '644a50b6721097dc09aa54c1',
    value: 'Pacific Standard Time',
    abbr: 'PST',
    offset: '-8',
    isdst: false,
    text: '(UTC-08:00) Pacific Standard Time (US & Canada)',
    utc: [
      'America/Los_Angeles',
      'America/Tijuana',
      'America/Vancouver',
      'PST8PDT',
    ],
    __v: 0,
  },
];
